-- =====================================================================
-- CUPPA — Supabase database schema (таны өөрийн ангилал/брэндэд тохируулсан)
-- Ажиллуулах газар: Supabase Dashboard → SQL Editor → New query → Run
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0) Хуучин хүснэгтүүдийг цэвэрлэх
-- ---------------------------------------------------------------------
drop table if exists order_items cascade;
drop table if exists orders cascade;
drop table if exists products cascade;
drop table if exists subcategories cascade;
drop table if exists brands cascade;
drop table if exists categories cascade;

-- ---------------------------------------------------------------------
-- 1) Хүснэгтүүд
-- ---------------------------------------------------------------------
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text default 'Coffee',
  created_at timestamptz default now()
);

create table subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references categories(id) on delete cascade,
  name text not null
);

create table brands (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);

create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand_id bigint references brands(id) on delete set null,
  category_id bigint references categories(id) on delete set null,
  subcategory text,
  origin text,
  tag text,
  color text default '#6B4226',
  description text,
  images jsonb default '[]'::jsonb,
  unit_label text,
  unit_price numeric default 0,
  unit_stock int default 0,
  box_label text,
  box_price numeric default 0,
  box_per_box int default 1,
  box_stock int default 0,
  created_at timestamptz default now()
);

create table orders (
  order_number text primary key,
  customer_name text,
  phone text,
  address text,
  subtotal numeric,
  status text default 'pending', -- pending | processing | shipped | done | cancelled
  created_at timestamptz default now()
);

create table order_items (
  id bigint generated by default as identity primary key,
  order_number text not null references orders(order_number) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_name text,
  option_type text, -- 'unit' | 'box'
  option_label text,
  unit_price numeric,
  qty int,
  line_total numeric
);

-- ---------------------------------------------------------------------
-- 2) Row Level Security
-- ---------------------------------------------------------------------
alter table categories enable row level security;
alter table subcategories enable row level security;
alter table brands enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

create policy "public read categories" on categories for select using (true);
create policy "public read subcategories" on subcategories for select using (true);
create policy "public read brands" on brands for select using (true);
create policy "public read products" on products for select using (true);

create policy "admin insert categories" on categories for insert with check (auth.role() = 'authenticated');
create policy "admin update categories" on categories for update using (auth.role() = 'authenticated');
create policy "admin delete categories" on categories for delete using (auth.role() = 'authenticated');

create policy "admin insert subcategories" on subcategories for insert with check (auth.role() = 'authenticated');
create policy "admin delete subcategories" on subcategories for delete using (auth.role() = 'authenticated');

create policy "admin insert brands" on brands for insert with check (auth.role() = 'authenticated');
create policy "admin delete brands" on brands for delete using (auth.role() = 'authenticated');

create policy "admin insert products" on products for insert with check (auth.role() = 'authenticated');
create policy "admin update products" on products for update using (auth.role() = 'authenticated');
create policy "admin delete products" on products for delete using (auth.role() = 'authenticated');

create policy "public create orders" on orders for insert with check (true);
create policy "admin read orders" on orders for select using (auth.role() = 'authenticated');
create policy "admin update orders" on orders for update using (auth.role() = 'authenticated');
create policy "admin delete orders" on orders for delete using (auth.role() = 'authenticated');

create policy "public create order_items" on order_items for insert with check (true);
create policy "admin read order_items" on order_items for select using (auth.role() = 'authenticated');
create policy "admin delete order_items" on order_items for delete using (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------
-- 3) Таны ангилал (6) — icon бүрд тохирсон утга өгсөн (доор жагсаалт: Coffee/Leaf/Droplet/Snowflake/Wrench)
-- ---------------------------------------------------------------------
insert into categories (name, icon) values
  ('Кофе', 'Coffee'),
  ('Цай', 'Leaf'),
  ('Сироп', 'Droplet'),
  ('Соус', 'Droplet'),
  ('Нунтаг', 'Snowflake'),
  ('Бариста хэрэгсэл', 'Wrench');

-- Дэд ангилал — санал болгож буй эхлэл, дараа нь Admin panel-аасаа хялбар
-- нэмэх/өөрчлөх боломжтой тул энд төгс байх шаардлагагүй
insert into subcategories (category_id, name)
  select id, s.name from categories, unnest(array['Light','Medium','Medium Dark','Dark']) as s(name) where categories.name = 'Кофе'
  union all
  select id, s.name from categories, unnest(array['Жимстэй цай' ,'Хар цай','Ногоон цай']) as s(name) where categories.name = 'Цай'
  union all
  select id, s.name from categories, unnest(array['Жимсний сироп','Чихрийн сироп']) as s(name) where categories.name = 'Сироп'
  union all
  select id, s.name from categories, unnest(array['Шоколад','Карамел']) as s(name) where categories.name = 'Соус'
  union all
  select id, s.name from categories, unnest(array['Шоколад','Матча','Тараг','Жимс']) as s(name) where categories.name = 'Нунтаг'
  union all
  select id, s.name from categories, unnest(array['Fortafilter/Tamper','Аяга/Таг','Цэвэрлэгээ']) as s(name) where categories.name = 'Бариста хэрэгсэл';

-- ---------------------------------------------------------------------
-- 4) Таны брэндүүд
-- ---------------------------------------------------------------------
insert into brands (name) values
  ('Pomona'), ('Hario'), ('Kalita'), ('UP'),
  ('Taco'), ('Daeho'), ('Sweet Page'), ('Nature Tea')
on conflict (name) do nothing;

-- Бараа энд оруулаагүй — Admin panel (admin-panel.html) дээрээсээ гараар нэмнэ үү.

-- ---------------------------------------------------------------------
-- 5) Барааны зураг хадгалах Storage bucket + policy
--    (drop if exists ашигласан тул дахин ажиллуулахад ч алдаа өгөхгүй)
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "public read product images" on storage.objects;
drop policy if exists "admin upload product images" on storage.objects;
drop policy if exists "admin delete product images" on storage.objects;

create policy "public read product images"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "admin upload product images"
  on storage.objects for insert
  with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

create policy "admin delete product images"
  on storage.objects for delete
  using (bucket_id = 'product-images' and auth.role() = 'authenticated');
